### PR TITLE
Add changes to footer and deploy

### LINKED ISSUE #207: Update Footer and Deploy Live
The footer can either be changed through the UI package or directly in the codebase for this site. (It may have already been updated in the UI package but is not pulling it correctly). 

Once you make the changes please share a testing URL for review.

Then it will need to be published so it is live on the main site on mybit.io and all of its pages (except the application which will have a slightly different footer).

Footer Updates: (make sure it is updated for every page on site)
a) change contact link from email to https://t.me/mybitio
b) rename first column "Site" instead of "MyBit Go"
c) remove token distribution from second column (resources)
d) remove the whole column called "social"
e) change 4th column title from "Go" to "MyBit" and button text to "Launch MyBit"
f) get rid of company address and replace with "MyBit is operated and maintained by a DAO" followed by (in blue text) "DAO address: 0xcD3d9b832BfF15E0a519610372c6AAC651872DdE" - and make the addresses linkable/clickable to: https://mainnet.aragon.org/#/0xcD3d9b832BfF15E0a519610372c6AAC651872DdE/
g) remove copyright in footer

### PR DESCRIPTION
**Pull request by mul53**
Closes #207 

Added margin fixes

### CODE REVIEW

**Comment by cryptnotiq** [comment]
@mul53 can you please generate a testing URL?

**Comment by mul53** [comment]
@cryptnotiq here it is [demo](https://laughing-euler-8937f9.netlify.com/), any changes needed?

**Comment by cryptnotiq** [comment]
Screen Shot 2020-01-23 at 23 21 55
Screen Shot 2020-01-23 at 23 21 45

@mul53 it's still cut-off and lets me drag it to see white space, which it shouldn't do.

**Comment by mul53** [comment]
ohh i see the problem, let me fix this right now

**Comment by mul53** [comment]
now works as intended  [demo](https://laughing-euler-8937f9.netlify.com/)

**Comment by cryptnotiq** [comment]
@mul53 still cut off.  can you just move it over more to the left?

Screen Shot 2020-01-24 at 14 37 53

**Comment by mul53** [comment]
@cryptnotiq i added the changes two days ago, [demo](https://laughing-euler-8937f9.netlify.com/)

**Comment by cryptnotiq** [comment]
@mul53 its still overflowing. Just add the same margin you have on the left side of the footer to the right side and it should fix it.

**Comment by mul53** [comment]
@cryptnotiq what device are you testing on? I will do that

**Comment by cryptnotiq** [comment]
@mul53 macbook pro, 15", Chrome and Brave

**Comment by mul53** [comment]
@cryptnotiq thanks for info, it was working in firefox then when i tried in chrome i saw what you were talking about. I have tested with chrome, i added a word-wrap. Confident it will work [demo](https://laughing-euler-8937f9.netlify.com/). I was busy earlier this week, i'm now free so we can finish this today

**Comment by cryptnotiq** [comment]
@mul53 it solved the overflow issue, but can you extend the margins so things aren't cut off onto 2 lines. 

i.e "by a dao" on the same line
and the dao address all on one line.

**Comment by mul53** [comment]
@cryptnotiq i have worked on it, the "by a dao" is on the same line and the address is on one line on desktop but is wrapped when the device screen is smaller like mobile it can't fit on the whole screen [demo](https://laughing-euler-8937f9.netlify.com/)

**Pull request merged**
